/********************************************************************
* VisuSLitraniDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error VisuSLitraniDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableVisuSLitraniDict();
extern void G__cpp_setup_inheritanceVisuSLitraniDict();
extern void G__cpp_setup_typetableVisuSLitraniDict();
extern void G__cpp_setup_memvarVisuSLitraniDict();
extern void G__cpp_setup_globalVisuSLitraniDict();
extern void G__cpp_setup_memfuncVisuSLitraniDict();
extern void G__cpp_setup_funcVisuSLitraniDict();
extern void G__set_cpp_environmentVisuSLitraniDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TVisuSLit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__VisuSLitraniDictLN_TClass;
extern G__linked_taginfo G__VisuSLitraniDictLN_TBuffer;
extern G__linked_taginfo G__VisuSLitraniDictLN_TMemberInspector;
extern G__linked_taginfo G__VisuSLitraniDictLN_TObject;
extern G__linked_taginfo G__VisuSLitraniDictLN_TString;
extern G__linked_taginfo G__VisuSLitraniDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__VisuSLitraniDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__VisuSLitraniDictLN_TObjArray;
extern G__linked_taginfo G__VisuSLitraniDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__VisuSLitraniDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__VisuSLitraniDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__VisuSLitraniDictLN_TFile;
extern G__linked_taginfo G__VisuSLitraniDictLN_TTree;
extern G__linked_taginfo G__VisuSLitraniDictLN_TBranch;
extern G__linked_taginfo G__VisuSLitraniDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__VisuSLitraniDictLN_TGObject;
extern G__linked_taginfo G__VisuSLitraniDictLN_TQObject;
extern G__linked_taginfo G__VisuSLitraniDictLN_TGWindow;
extern G__linked_taginfo G__VisuSLitraniDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__VisuSLitraniDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__VisuSLitraniDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__VisuSLitraniDictLN_TGFrame;
extern G__linked_taginfo G__VisuSLitraniDictLN_TGCompositeFrame;
extern G__linked_taginfo G__VisuSLitraniDictLN_TGLayoutHints;
extern G__linked_taginfo G__VisuSLitraniDictLN_TGTextButton;
extern G__linked_taginfo G__VisuSLitraniDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__VisuSLitraniDictLN_TGMainFrame;
extern G__linked_taginfo G__VisuSLitraniDictLN_TGGroupFrame;
extern G__linked_taginfo G__VisuSLitraniDictLN_TGPopupMenu;
extern G__linked_taginfo G__VisuSLitraniDictLN_TGMenuBar;
extern G__linked_taginfo G__VisuSLitraniDictLN_TCanvas;
extern G__linked_taginfo G__VisuSLitraniDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__VisuSLitraniDictLN_TGRadioButton;
extern G__linked_taginfo G__VisuSLitraniDictLN_TGListBox;
extern G__linked_taginfo G__VisuSLitraniDictLN_TGFileInfo;
extern G__linked_taginfo G__VisuSLitraniDictLN_TReference;
extern G__linked_taginfo G__VisuSLitraniDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__VisuSLitraniDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__VisuSLitraniDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__VisuSLitraniDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__VisuSLitraniDictLN_TLitResults;
extern G__linked_taginfo G__VisuSLitraniDictLN_ToBeDrawn;
extern G__linked_taginfo G__VisuSLitraniDictLN_TVisuSLit;

/* STUB derived class for protected member access */
