//
// File generated by /home/michael/root/bin/rootcint at Fri Sep 27 08:21:53 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME VisuSLitraniDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "VisuSLitraniDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TVisuSLit_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TVisuSLit(void *p = 0);
   static void *newArray_TVisuSLit(Long_t size, void *p);
   static void delete_TVisuSLit(void *p);
   static void deleteArray_TVisuSLit(void *p);
   static void destruct_TVisuSLit(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TVisuSLit*)
   {
      ::TVisuSLit *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TVisuSLit >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TVisuSLit", ::TVisuSLit::Class_Version(), "./TVisuSLit.h", 31,
                  typeid(::TVisuSLit), DefineBehavior(ptr, ptr),
                  &::TVisuSLit::Dictionary, isa_proxy, 4,
                  sizeof(::TVisuSLit) );
      instance.SetNew(&new_TVisuSLit);
      instance.SetNewArray(&newArray_TVisuSLit);
      instance.SetDelete(&delete_TVisuSLit);
      instance.SetDeleteArray(&deleteArray_TVisuSLit);
      instance.SetDestructor(&destruct_TVisuSLit);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TVisuSLit*)
   {
      return GenerateInitInstanceLocal((::TVisuSLit*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TVisuSLit*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TVisuSLit::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TVisuSLit::Class_Name()
{
   return "TVisuSLit";
}

//______________________________________________________________________________
const char *TVisuSLit::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TVisuSLit*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TVisuSLit::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TVisuSLit*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TVisuSLit::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TVisuSLit*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TVisuSLit::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TVisuSLit*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TVisuSLit::Streamer(TBuffer &R__b)
{
   // Stream an object of class TVisuSLit.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(TVisuSLit::Class(),this);
   } else {
      R__b.WriteClassBuffer(TVisuSLit::Class(),this);
   }
}

//______________________________________________________________________________
void TVisuSLit::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TVisuSLit.
      TClass *R__cl = ::TVisuSLit::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fWidthGen", &fWidthGen);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fHeigthGen", &fHeigthGen);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNFits", &fNFits);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fKFit", &fKFit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fFitColl", &fFitColl);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNSpecs", &fNSpecs);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fKSpec", &fKSpec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fSpecColl", &fSpecColl);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fRef", &fRef);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCanvas", &fCanvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDate", &fDate);
      R__insp.InspectMember(fDate, "fDate.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTime", &fTime);
      R__insp.InspectMember(fTime, "fTime.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fBTRchanged", &fBTRchanged);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTextBR", &fTextBR);
      R__insp.InspectMember(fTextBR, "fTextBR.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fInColor", &fInColor);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fFileClosed", &fFileClosed);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fFileName", &fFileName);
      R__insp.InspectMember(fFileName, "fFileName.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fLitFile", &fLitFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fLitBufSize", &fLitBufSize);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fLitNb", &fLitNb);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fLitTree", &fLitTree);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fLitBranch", &fLitBranch);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fListRuns", &fListRuns);
      R__insp.InspectMember(fListRuns, "fListRuns.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDrawChoice", &fDrawChoice);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fLMenu", &fLMenu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fLMenuItem", &fLMenuItem);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fFi", &fFi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMenuBar", &fMenuBar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMenuFile", &fMenuFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fL1", &fL1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fL2", &fL2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fL3", &fL3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fL4", &fL4);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fL5", &fL5);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fL6", &fL6);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fL7", &fL7);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fL8", &fL8);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHFrame1", &fHFrame1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHFrame2", &fHFrame2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fEcanvas", &fEcanvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fDrawButton", &fDrawButton);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fStatButton", &fStatButton);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fOneTwoButton", &fOneTwoButton);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fLinLogButton", &fLinLogButton);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fColorButton", &fColorButton);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fPrintButton", &fPrintButton);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fListBox", &fListBox);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fListBoxItem", &fListBoxItem);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fButtonGroup", &fButtonGroup);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fRadioPar", &fRadioPar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fRadioRun", &fRadioRun);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fRadioDet", &fRadioDet);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fRadioFit", &fRadioFit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fRadioSpec", &fRadioSpec);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TVisuSLit(void *p) {
      return  p ? new(p) ::TVisuSLit : new ::TVisuSLit;
   }
   static void *newArray_TVisuSLit(Long_t nElements, void *p) {
      return p ? new(p) ::TVisuSLit[nElements] : new ::TVisuSLit[nElements];
   }
   // Wrapper around operator delete
   static void delete_TVisuSLit(void *p) {
      delete ((::TVisuSLit*)p);
   }
   static void deleteArray_TVisuSLit(void *p) {
      delete [] ((::TVisuSLit*)p);
   }
   static void destruct_TVisuSLit(void *p) {
      typedef ::TVisuSLit current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TVisuSLit

/********************************************************
* VisuSLitraniDict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableVisuSLitraniDict();

extern "C" void G__set_cpp_environmentVisuSLitraniDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TVisuSLit.h");
  G__cpp_reset_tagtableVisuSLitraniDict();
}
#include <new>
extern "C" int G__cpp_dllrevVisuSLitraniDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TVisuSLit */
static int G__VisuSLitraniDict_720_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TVisuSLit* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TVisuSLit[n];
     } else {
       p = new((void*) gvp) TVisuSLit[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TVisuSLit;
     } else {
       p = new((void*) gvp) TVisuSLit;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TVisuSLit));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TVisuSLit* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TVisuSLit(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) TVisuSLit(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TVisuSLit));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVisuSLit*) G__getstructoffset())->ChangePadLogX();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVisuSLit*) G__getstructoffset())->ChangePadLogY();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVisuSLit*) G__getstructoffset())->DoDraw();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVisuSLit*) G__getstructoffset())->DoRadio();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVisuSLit*) G__getstructoffset())->DoStat();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVisuSLit*) G__getstructoffset())->DrawNextFit();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVisuSLit*) G__getstructoffset())->DrawNextSpectrum();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TVisuSLit*) G__getstructoffset())->GetCanvas());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const TVisuSLit*) G__getstructoffset())->GetHeigthGen());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TVisuSLit*) G__getstructoffset())->GetRef());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const TVisuSLit*) G__getstructoffset())->GetWidthGen());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVisuSLit*) G__getstructoffset())->HandleMenu((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVisuSLit*) G__getstructoffset())->PrintCanvas();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVisuSLit*) G__getstructoffset())->ToggleColor();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVisuSLit*) G__getstructoffset())->ToggleState();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TVisuSLit::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TVisuSLit::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TVisuSLit::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TVisuSLit::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVisuSLit*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TVisuSLit::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TVisuSLit::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TVisuSLit::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__VisuSLitraniDict_720_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TVisuSLit::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TVisuSLit G__TTVisuSLit;
static int G__VisuSLitraniDict_720_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TVisuSLit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TVisuSLit*) (soff+(sizeof(TVisuSLit)*i)))->~G__TTVisuSLit();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TVisuSLit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TVisuSLit*) (soff))->~G__TTVisuSLit();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TVisuSLit */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncVisuSLitraniDict {
 public:
  G__Sizep2memfuncVisuSLitraniDict(): p(&G__Sizep2memfuncVisuSLitraniDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncVisuSLitraniDict::*p)();
};

size_t G__get_sizep2memfuncVisuSLitraniDict()
{
  G__Sizep2memfuncVisuSLitraniDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceVisuSLitraniDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__VisuSLitraniDictLN_TVisuSLit))) {
     TVisuSLit *G__Lderived;
     G__Lderived=(TVisuSLit*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__VisuSLitraniDictLN_TVisuSLit),G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__VisuSLitraniDictLN_TVisuSLit),G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__VisuSLitraniDictLN_TVisuSLit),G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__VisuSLitraniDictLN_TVisuSLit),G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__VisuSLitraniDictLN_TVisuSLit),G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__VisuSLitraniDictLN_TVisuSLit),G__get_linked_tagnum(&G__VisuSLitraniDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__VisuSLitraniDictLN_TVisuSLit),G__get_linked_tagnum(&G__VisuSLitraniDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableVisuSLitraniDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TVisuSLit */
static void G__setup_memvarTVisuSLit(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__VisuSLitraniDictLN_TVisuSLit));
   { TVisuSLit *p; p=(TVisuSLit*)0x1000; if (p) { }
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("UInt_t"),-1,2,"fWidthGen=",0,"Width  of general canvas fCanvas");
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("UInt_t"),-1,2,"fHeigthGen=",0,"Heigth of general canvas fCanvas");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"fNFits=",0,"Number of fits in fFitColl");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"fKFit=",0,"Counter of fits drawn");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TObjArray),-1,-1,2,"fFitColl=",0,"Collection of fits");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"fNSpecs=",0,"Number of spectra in fSpecColl");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"fKSpec=",0,"Counter of spectra drawn");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TObjArray),-1,-1,2,"fSpecColl=",0,"Collection of spectra");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TReference),-1,-1,2,"fRef=",0,"References concerning program and authors");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TCanvas),-1,-1,2,"fCanvas=",0,"Canvas of fECanvas");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TString),-1,-1,2,"fDate=",0,"date of to-day put in 3rd label");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TString),-1,-1,2,"fTime=",0,"Time when program runs");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,2,"fBTRchanged=",0,"True if comments BR and TR have changed");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TString),-1,-1,2,"fTextBR=",0,"Initial bottom right label");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,2,"fInColor=",0,"True if display in color, not in grey");
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,2,"fFileClosed=",0,"True if SLitrani file has been closed");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TString),-1,-1,2,"fFileName=",0,"Name of file to open");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TFile),-1,-1,2,"fLitFile=",0,"SLitrani file to be read");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"fLitBufSize=",0,"buffer size of file");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"fLitNb=",0,"pointer on actual size of file");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TTree),-1,-1,2,"fLitTree=",0,"tree of histos and statistics for each run.");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TBranch),-1,-1,2,"fLitBranch=",0,"branch of tree");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TObjArray),-1,-1,2,"fListRuns=",0,"collection of runs");
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_ToBeDrawn),-1,-1,2,"fDrawChoice=",0,"Kind of histos to be plotted");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGLayoutHints),-1,-1,2,"fLMenu=",0,"Layout of menu bar");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGLayoutHints),-1,-1,2,"fLMenuItem=",0,"Layout of left menus in menu bar");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGFileInfo),-1,-1,2,"fFi=",0,"Used in meu File/Open");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGMenuBar),-1,-1,2,"fMenuBar=",0,"Bar holding menus");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGPopupMenu),-1,-1,2,"fMenuFile=",0,"File menu");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGLayoutHints),-1,-1,2,"fL1=",0,"Layout of fEcanvas in fHFrame1");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGLayoutHints),-1,-1,2,"fL2=",0,"Layout of fHFrame1 in this");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGLayoutHints),-1,-1,2,"fL3=",0,"Layout of fDrawButton in fHFrame2");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGLayoutHints),-1,-1,2,"fL4=",0,"Layout of fStatButton in fHFrame2");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGLayoutHints),-1,-1,2,"fL5=",0,"Layout of fHFrame2 in this");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGLayoutHints),-1,-1,2,"fL6=",0,"Layout of fListBox in fHFrame1");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGLayoutHints),-1,-1,2,"fL7=",0,"Layout of fButtonGroup in fHFrame2");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGLayoutHints),-1,-1,2,"fL8=",0,"Layout of radio buttons in fButtonGroup");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGHorizontalFrame),-1,-1,2,"fHFrame1=",0,"Horizontal frame up");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGHorizontalFrame),-1,-1,2,"fHFrame2=",0,"Horizontal frame down");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TRootEmbeddedCanvas),-1,-1,2,"fEcanvas=",0,"RootEmbeddedCanvas in fHFrame1, at right");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGTextButton),-1,-1,2,"fDrawButton=",0,"Draw Button");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGTextButton),-1,-1,2,"fStatButton=",0,"Plot statistics Button");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGTextButton),-1,-1,2,"fOneTwoButton=",0,"Change from 2 pads to 1 pad or vice-versa");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGTextButton),-1,-1,2,"fLinLogButton=",0,"Switch from linear Y log scale to logarithmic or vice-versa");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGTextButton),-1,-1,2,"fColorButton=",0,"Change display from color to grey or vice-versa");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGTextButton),-1,-1,2,"fPrintButton=",0,"Save canvas of VisuLitrani");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGListBox),-1,-1,2,"fListBox=",0,"List Box showing all runs in file");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"fListBoxItem=",0,"Item selected in fListBox");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGGroupFrame),-1,-1,2,"fButtonGroup=",0,"Contains list of radio buttons");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGRadioButton),-1,-1,2,"fRadioPar=",0,"Choosing display of results versus run-dependent parameter");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGRadioButton),-1,-1,2,"fRadioRun=",0,"Choosing display of results for a specific run or sum of all runs");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGRadioButton),-1,-1,2,"fRadioDet=",0,"Choosing display of results of detectors for a specific run or sum of all runs");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGRadioButton),-1,-1,2,"fRadioFit=",0,"Choosing display of fits of type TSplineFit used for this generation of photons");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TGRadioButton),-1,-1,2,"fRadioSpec=",0,"Choosing display of spectra of type TLitSpectrum used for this generation of photons");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__VisuSLitraniDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarVisuSLitraniDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTVisuSLit(void) {
   /* TVisuSLit */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__VisuSLitraniDictLN_TVisuSLit));
   G__memfunc_setup("BookCanvas",999,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CloseFile",886,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "g - 'Bool_t' 0 'kTRUE' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FirstRead",900,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitP",484,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitRef",689,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OpenFileR",868,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrepareMenus",1239,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SelectRun",917,(G__InterfaceMethod) NULL, 85, G__get_linked_tagnum(&G__VisuSLitraniDictLN_TLitResults), -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TVisuSLit",887,G__VisuSLitraniDict_720_0_10, 105, G__get_linked_tagnum(&G__VisuSLitraniDictLN_TVisuSLit), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TVisuSLit",887,G__VisuSLitraniDict_720_0_11, 105, G__get_linked_tagnum(&G__VisuSLitraniDictLN_TVisuSLit), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangePadLogX",1237,G__VisuSLitraniDict_720_0_12, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangePadLogY",1238,G__VisuSLitraniDict_720_0_13, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoDraw",577,G__VisuSLitraniDict_720_0_14, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoRadio",674,G__VisuSLitraniDict_720_0_15, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoStat",591,G__VisuSLitraniDict_720_0_16, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawNextFit",1104,G__VisuSLitraniDict_720_0_17, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawNextSpectrum",1664,G__VisuSLitraniDict_720_0_18, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCanvas",892,G__VisuSLitraniDict_720_0_19, 85, G__get_linked_tagnum(&G__VisuSLitraniDictLN_TCanvas), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHeigthGen",1171,G__VisuSLitraniDict_720_0_20, 104, -1, G__defined_typename("UInt_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRef",573,G__VisuSLitraniDict_720_0_21, 85, G__get_linked_tagnum(&G__VisuSLitraniDictLN_TReference), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWidthGen",1082,G__VisuSLitraniDict_720_0_22, 104, -1, G__defined_typename("UInt_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HandleMenu",993,G__VisuSLitraniDict_720_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintCanvas",1129,G__VisuSLitraniDict_720_0_24, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ToggleColor",1121,G__VisuSLitraniDict_720_0_25, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ToggleState",1123,G__VisuSLitraniDict_720_0_26, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__VisuSLitraniDict_720_0_27, 85, G__get_linked_tagnum(&G__VisuSLitraniDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TVisuSLit::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__VisuSLitraniDict_720_0_28, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TVisuSLit::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__VisuSLitraniDict_720_0_29, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TVisuSLit::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__VisuSLitraniDict_720_0_30, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TVisuSLit::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__VisuSLitraniDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__VisuSLitraniDict_720_0_34, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__VisuSLitraniDict_720_0_35, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TVisuSLit::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__VisuSLitraniDict_720_0_36, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TVisuSLit::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__VisuSLitraniDict_720_0_37, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TVisuSLit::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__VisuSLitraniDict_720_0_38, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TVisuSLit::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~TVisuSLit", 1013, G__VisuSLitraniDict_720_0_39, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncVisuSLitraniDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalVisuSLitraniDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcVisuSLitraniDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__VisuSLitraniDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TObjArray = { "TObjArray" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TBranch = { "TBranch" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TGLayoutHints = { "TGLayoutHints" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TGHorizontalFrame = { "TGHorizontalFrame" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TGGroupFrame = { "TGGroupFrame" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TGPopupMenu = { "TGPopupMenu" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TGMenuBar = { "TGMenuBar" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TGRadioButton = { "TGRadioButton" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TGListBox = { "TGListBox" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TGFileInfo = { "TGFileInfo" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TReference = { "TReference" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TLitResults = { "TLitResults" , 99 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_ToBeDrawn = { "ToBeDrawn" , 101 , -1 };
G__linked_taginfo G__VisuSLitraniDictLN_TVisuSLit = { "TVisuSLit" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableVisuSLitraniDict() {
  G__VisuSLitraniDictLN_TClass.tagnum = -1 ;
  G__VisuSLitraniDictLN_TBuffer.tagnum = -1 ;
  G__VisuSLitraniDictLN_TMemberInspector.tagnum = -1 ;
  G__VisuSLitraniDictLN_TObject.tagnum = -1 ;
  G__VisuSLitraniDictLN_TString.tagnum = -1 ;
  G__VisuSLitraniDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__VisuSLitraniDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__VisuSLitraniDictLN_TObjArray.tagnum = -1 ;
  G__VisuSLitraniDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__VisuSLitraniDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__VisuSLitraniDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__VisuSLitraniDictLN_TFile.tagnum = -1 ;
  G__VisuSLitraniDictLN_TTree.tagnum = -1 ;
  G__VisuSLitraniDictLN_TBranch.tagnum = -1 ;
  G__VisuSLitraniDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__VisuSLitraniDictLN_TGObject.tagnum = -1 ;
  G__VisuSLitraniDictLN_TQObject.tagnum = -1 ;
  G__VisuSLitraniDictLN_TGWindow.tagnum = -1 ;
  G__VisuSLitraniDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__VisuSLitraniDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__VisuSLitraniDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__VisuSLitraniDictLN_TGFrame.tagnum = -1 ;
  G__VisuSLitraniDictLN_TGCompositeFrame.tagnum = -1 ;
  G__VisuSLitraniDictLN_TGLayoutHints.tagnum = -1 ;
  G__VisuSLitraniDictLN_TGTextButton.tagnum = -1 ;
  G__VisuSLitraniDictLN_TGHorizontalFrame.tagnum = -1 ;
  G__VisuSLitraniDictLN_TGMainFrame.tagnum = -1 ;
  G__VisuSLitraniDictLN_TGGroupFrame.tagnum = -1 ;
  G__VisuSLitraniDictLN_TGPopupMenu.tagnum = -1 ;
  G__VisuSLitraniDictLN_TGMenuBar.tagnum = -1 ;
  G__VisuSLitraniDictLN_TCanvas.tagnum = -1 ;
  G__VisuSLitraniDictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__VisuSLitraniDictLN_TGRadioButton.tagnum = -1 ;
  G__VisuSLitraniDictLN_TGListBox.tagnum = -1 ;
  G__VisuSLitraniDictLN_TGFileInfo.tagnum = -1 ;
  G__VisuSLitraniDictLN_TReference.tagnum = -1 ;
  G__VisuSLitraniDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__VisuSLitraniDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__VisuSLitraniDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__VisuSLitraniDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__VisuSLitraniDictLN_TLitResults.tagnum = -1 ;
  G__VisuSLitraniDictLN_ToBeDrawn.tagnum = -1 ;
  G__VisuSLitraniDictLN_TVisuSLit.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableVisuSLitraniDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TString);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TObjArray);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TFile);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TTree);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TBranch);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TGLayoutHints);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TGHorizontalFrame);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TGGroupFrame);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TGPopupMenu);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TGMenuBar);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TGRadioButton);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TGListBox);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TGFileInfo);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TReference);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TLitResults);
   G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_ToBeDrawn);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__VisuSLitraniDictLN_TVisuSLit),sizeof(TVisuSLit),-1,324864,"Visualize the ROOT files produced by SLitrani",G__setup_memvarTVisuSLit,G__setup_memfuncTVisuSLit);
}
extern "C" void G__cpp_setupVisuSLitraniDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupVisuSLitraniDict()");
  G__set_cpp_environmentVisuSLitraniDict();
  G__cpp_setup_tagtableVisuSLitraniDict();

  G__cpp_setup_inheritanceVisuSLitraniDict();

  G__cpp_setup_typetableVisuSLitraniDict();

  G__cpp_setup_memvarVisuSLitraniDict();

  G__cpp_setup_memfuncVisuSLitraniDict();
  G__cpp_setup_globalVisuSLitraniDict();
  G__cpp_setup_funcVisuSLitraniDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncVisuSLitraniDict();
  return;
}
class G__cpp_setup_initVisuSLitraniDict {
  public:
    G__cpp_setup_initVisuSLitraniDict() { G__add_setup_func("VisuSLitraniDict",(G__incsetup)(&G__cpp_setupVisuSLitraniDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initVisuSLitraniDict() { G__remove_setup_func("VisuSLitraniDict"); }
};
G__cpp_setup_initVisuSLitraniDict G__cpp_setup_initializerVisuSLitraniDict;

