/********************************************************************
* SplineFitDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SplineFitDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSplineFitDict();
extern void G__cpp_setup_inheritanceSplineFitDict();
extern void G__cpp_setup_typetableSplineFitDict();
extern void G__cpp_setup_memvarSplineFitDict();
extern void G__cpp_setup_globalSplineFitDict();
extern void G__cpp_setup_memfuncSplineFitDict();
extern void G__cpp_setup_funcSplineFitDict();
extern void G__set_cpp_environmentSplineFitDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TPoly3.h"
#include "TBandedLE.h"
#include "TZigZag.h"
#include "TSplineFit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SplineFitDictLN_TClass;
extern G__linked_taginfo G__SplineFitDictLN_TBuffer;
extern G__linked_taginfo G__SplineFitDictLN_TMemberInspector;
extern G__linked_taginfo G__SplineFitDictLN_TObject;
extern G__linked_taginfo G__SplineFitDictLN_TNamed;
extern G__linked_taginfo G__SplineFitDictLN_TString;
extern G__linked_taginfo G__SplineFitDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SplineFitDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SplineFitDictLN_TObjArray;
extern G__linked_taginfo G__SplineFitDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SplineFitDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SplineFitDictLN_TPoly3;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__SplineFitDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__SplineFitDictLN_TBandedLE;
extern G__linked_taginfo G__SplineFitDictLN_TArrayI;
extern G__linked_taginfo G__SplineFitDictLN_TArrayD;
extern G__linked_taginfo G__SplineFitDictLN_TZigZag;
extern G__linked_taginfo G__SplineFitDictLN_TH1;
extern G__linked_taginfo G__SplineFitDictLN_TF1;
extern G__linked_taginfo G__SplineFitDictLN_TGraph;
extern G__linked_taginfo G__SplineFitDictLN_TGraphErrors;
extern G__linked_taginfo G__SplineFitDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SplineFitDictLN_TMultiGraph;
extern G__linked_taginfo G__SplineFitDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__SplineFitDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__SplineFitDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SplineFitDictLN_TFile;
extern G__linked_taginfo G__SplineFitDictLN_TTree;
extern G__linked_taginfo G__SplineFitDictLN_TBranch;
extern G__linked_taginfo G__SplineFitDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__SplineFitDictLN_TH1D;
extern G__linked_taginfo G__SplineFitDictLN_TH2D;
extern G__linked_taginfo G__SplineFitDictLN_TH3D;
extern G__linked_taginfo G__SplineFitDictLN_TSpline3;
extern G__linked_taginfo G__SplineFitDictLN_TReference;
extern G__linked_taginfo G__SplineFitDictLN_KindOfFit;
extern G__linked_taginfo G__SplineFitDictLN_TSplineFit;

/* STUB derived class for protected member access */
