/********************************************************************
* PhysMoreDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PhysMoreDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePhysMoreDict();
extern void G__cpp_setup_inheritancePhysMoreDict();
extern void G__cpp_setup_typetablePhysMoreDict();
extern void G__cpp_setup_memvarPhysMoreDict();
extern void G__cpp_setup_globalPhysMoreDict();
extern void G__cpp_setup_memfuncPhysMoreDict();
extern void G__cpp_setup_funcPhysMoreDict();
extern void G__set_cpp_environmentPhysMoreDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TArrayZ.h"
#include "TNArray.h"
#include "TCleanOut.h"
#include "TMat33.h"
#include "TEuler.h"
#include "TVec3C.h"
#include "TMat33C.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PhysMoreDictLN_TClass;
extern G__linked_taginfo G__PhysMoreDictLN_TBuffer;
extern G__linked_taginfo G__PhysMoreDictLN_TMemberInspector;
extern G__linked_taginfo G__PhysMoreDictLN_TObject;
extern G__linked_taginfo G__PhysMoreDictLN_TString;
extern G__linked_taginfo G__PhysMoreDictLN_basic_istreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__PhysMoreDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__PhysMoreDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__PhysMoreDictLN_string;
extern G__linked_taginfo G__PhysMoreDictLN_basic_stringbuflEcharcOchar_traitslEchargRcOallocatorlEchargRsPgR;
extern G__linked_taginfo G__PhysMoreDictLN_basic_ostringstreamlEcharcOchar_traitslEchargRcOallocatorlEchargRsPgR;
extern G__linked_taginfo G__PhysMoreDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PhysMoreDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PhysMoreDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PhysMoreDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PhysMoreDictLN_TComplex;
extern G__linked_taginfo G__PhysMoreDictLN_TArrayZ;
extern G__linked_taginfo G__PhysMoreDictLN_TNArraylEchargR;
extern G__linked_taginfo G__PhysMoreDictLN_TNArraylEshortgR;
extern G__linked_taginfo G__PhysMoreDictLN_TNArraylEintgR;
extern G__linked_taginfo G__PhysMoreDictLN_TNArraylElonggR;
extern G__linked_taginfo G__PhysMoreDictLN_TNArraylElongsPlonggR;
extern G__linked_taginfo G__PhysMoreDictLN_TNArraylEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TNArraylEdoublegR;
extern G__linked_taginfo G__PhysMoreDictLN_TNArraylETComplexgR;
extern G__linked_taginfo G__PhysMoreDictLN_KindOfMessage;
extern G__linked_taginfo G__PhysMoreDictLN_TCleanOut;
extern G__linked_taginfo G__PhysMoreDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__PhysMoreDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__PhysMoreDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__PhysMoreDictLN_TVector3;
extern G__linked_taginfo G__PhysMoreDictLN_TVec3C;
extern G__linked_taginfo G__PhysMoreDictLN_TMat33;
extern G__linked_taginfo G__PhysMoreDictLN_TEuler;
extern G__linked_taginfo G__PhysMoreDictLN_TMat33C;

/* STUB derived class for protected member access */
typedef TNArray<char> G__TNArraylEchargR;
typedef TNArray<short> G__TNArraylEshortgR;
typedef TNArray<int> G__TNArraylEintgR;
typedef TNArray<long> G__TNArraylElonggR;
typedef TNArray<long long> G__TNArraylElongsPlonggR;
typedef TNArray<float> G__TNArraylEfloatgR;
typedef TNArray<double> G__TNArraylEdoublegR;
typedef TNArray<TComplex> G__TNArraylETComplexgR;
