/********************************************************************
* TwoPadDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TwoPadDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTwoPadDict();
extern void G__cpp_setup_inheritanceTwoPadDict();
extern void G__cpp_setup_typetableTwoPadDict();
extern void G__cpp_setup_memvarTwoPadDict();
extern void G__cpp_setup_globalTwoPadDict();
extern void G__cpp_setup_memfuncTwoPadDict();
extern void G__cpp_setup_funcTwoPadDict();
extern void G__set_cpp_environmentTwoPadDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGRootIDE.h"
#include "TAuthor.h"
#include "TReference.h"
#include "TwoPadDisplay.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TwoPadDictLN_TClass;
extern G__linked_taginfo G__TwoPadDictLN_TBuffer;
extern G__linked_taginfo G__TwoPadDictLN_TMemberInspector;
extern G__linked_taginfo G__TwoPadDictLN_TObject;
extern G__linked_taginfo G__TwoPadDictLN_TNamed;
extern G__linked_taginfo G__TwoPadDictLN_TString;
extern G__linked_taginfo G__TwoPadDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TwoPadDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TwoPadDictLN_TObjArray;
extern G__linked_taginfo G__TwoPadDictLN_TTimer;
extern G__linked_taginfo G__TwoPadDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TwoPadDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TwoPadDictLN_Event_t;
extern G__linked_taginfo G__TwoPadDictLN_TGObject;
extern G__linked_taginfo G__TwoPadDictLN_TQObject;
extern G__linked_taginfo G__TwoPadDictLN_TGWindow;
extern G__linked_taginfo G__TwoPadDictLN_TAttLine;
extern G__linked_taginfo G__TwoPadDictLN_TAttFill;
extern G__linked_taginfo G__TwoPadDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__TwoPadDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__TwoPadDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TwoPadDictLN_TGFrame;
extern G__linked_taginfo G__TwoPadDictLN_TGCompositeFrame;
extern G__linked_taginfo G__TwoPadDictLN_TGLayoutHints;
extern G__linked_taginfo G__TwoPadDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TwoPadDictLN_TGVerticalFrame;
extern G__linked_taginfo G__TwoPadDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__TwoPadDictLN_TGMainFrame;
extern G__linked_taginfo G__TwoPadDictLN_TGText;
extern G__linked_taginfo G__TwoPadDictLN_TGTextView;
extern G__linked_taginfo G__TwoPadDictLN_TGPopupMenu;
extern G__linked_taginfo G__TwoPadDictLN_TGTextEdit;
extern G__linked_taginfo G__TwoPadDictLN_TGToolBar;
extern G__linked_taginfo G__TwoPadDictLN_TGStatusBar;
extern G__linked_taginfo G__TwoPadDictLN_TGMenuBar;
extern G__linked_taginfo G__TwoPadDictLN_TMacro;
extern G__linked_taginfo G__TwoPadDictLN_TGTextEntry;
extern G__linked_taginfo G__TwoPadDictLN_TGComboBox;
extern G__linked_taginfo G__TwoPadDictLN_TGTextBuffer;
extern G__linked_taginfo G__TwoPadDictLN_TGTab;
extern G__linked_taginfo G__TwoPadDictLN_TGFileContainer;
extern G__linked_taginfo G__TwoPadDictLN_TGLVEntry;
extern G__linked_taginfo G__TwoPadDictLN_TGTabElement;
extern G__linked_taginfo G__TwoPadDictLN_TGPictureButton;
extern G__linked_taginfo G__TwoPadDictLN_THtml;
extern G__linked_taginfo G__TwoPadDictLN_TGLabel;
extern G__linked_taginfo G__TwoPadDictLN_TGHtml;
extern G__linked_taginfo G__TwoPadDictLN_TGDocument;
extern G__linked_taginfo G__TwoPadDictLN_TGRootIDE;
extern G__linked_taginfo G__TwoPadDictLN_TAuthor;
extern G__linked_taginfo G__TwoPadDictLN_TReference;
extern G__linked_taginfo G__TwoPadDictLN_TLatex;
extern G__linked_taginfo G__TwoPadDictLN_TAttPad;
extern G__linked_taginfo G__TwoPadDictLN_TCanvas;
extern G__linked_taginfo G__TwoPadDictLN_TVirtualPad;
extern G__linked_taginfo G__TwoPadDictLN_TPad;
extern G__linked_taginfo G__TwoPadDictLN_TButton;
extern G__linked_taginfo G__TwoPadDictLN_StateOfPads;
extern G__linked_taginfo G__TwoPadDictLN_TwoPadDisplay;

/* STUB derived class for protected member access */
